dist: trusty
arch: [ amd64, ppc64le ]
notifications:
  email:
    recipients:
      - groonga-commit@lists.sourceforge.jp
language: c

install:
  - sudo apt-get update -y
  - sudo apt install lsb-release wget -y
  
script:
  - echo ""
